
package com.messagemedia.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "faultResponse", targetNamespace = "http://xml.m4u.com.au/2009")
public class FaultResponse
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultResponseType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FaultResponse(String message, FaultResponseType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FaultResponse(String message, FaultResponseType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.messagemedia.service.FaultResponseType
     */
    public FaultResponseType getFaultInfo() {
        return faultInfo;
    }

}
