
package com.messagemedia.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MessageMediaService", targetNamespace = "http://xml.m4u.com.au/2009", wsdlLocation = "https://soap.m4u.com.au/?wsdl")
public class MessageMediaService
    extends Service
{

    private final static URL MESSAGEMEDIASERVICE_WSDL_LOCATION;
    private final static WebServiceException MESSAGEMEDIASERVICE_EXCEPTION;
    private final static QName MESSAGEMEDIASERVICE_QNAME = new QName("http://xml.m4u.com.au/2009", "MessageMediaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://soap.m4u.com.au/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MESSAGEMEDIASERVICE_WSDL_LOCATION = url;
        MESSAGEMEDIASERVICE_EXCEPTION = e;
    }

    public MessageMediaService() {
        super(__getWsdlLocation(), MESSAGEMEDIASERVICE_QNAME);
    }

    public MessageMediaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MESSAGEMEDIASERVICE_QNAME, features);
    }

    public MessageMediaService(URL wsdlLocation) {
        super(wsdlLocation, MESSAGEMEDIASERVICE_QNAME);
    }

    public MessageMediaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MESSAGEMEDIASERVICE_QNAME, features);
    }

    public MessageMediaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessageMediaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MessageMediaServiceInterface
     */
    @WebEndpoint(name = "MessageMediaServiceEndPoint")
    public MessageMediaServiceInterface getMessageMediaServiceEndPoint() {
        return super.getPort(new QName("http://xml.m4u.com.au/2009", "MessageMediaServiceEndPoint"), MessageMediaServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MessageMediaServiceInterface
     */
    @WebEndpoint(name = "MessageMediaServiceEndPoint")
    public MessageMediaServiceInterface getMessageMediaServiceEndPoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://xml.m4u.com.au/2009", "MessageMediaServiceEndPoint"), MessageMediaServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MESSAGEMEDIASERVICE_EXCEPTION!= null) {
            throw MESSAGEMEDIASERVICE_EXCEPTION;
        }
        return MESSAGEMEDIASERVICE_WSDL_LOCATION;
    }

}
